---
# tasks file for nginx

- name: Add Nginx Repository
  yum_repository:
    name: Nginx
    description: Nginx Centos Repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: no
    enabled: yes
  become: yes

- name: Ensure Nginx Installed
  yum: name=nginx  
  become: yes

- name: change config
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - nginx restart

- name: jenkins config
  become: yes
  template:
    src: jenkins.conf.j2
    dest: /etc/nginx/conf.d/jenkins.conf        
  notify:
    - nginx restart   

- name: sonar config
  become: yes
  template:
    src: sonar.conf.j2
    dest: /etc/nginx/conf.d/sonar.conf        
  notify:
    - nginx restart

- name: nexus config
  become: yes
  template:
    src: nexus.conf.j2
    dest: /etc/nginx/conf.d/nexus.conf        
  notify:
    - nginx restart

- name: tomcat config
  become: yes
  template:
    src: tomcat.conf.j2
    dest: /etc/nginx/conf.d/tomcat.conf        
  notify:
    - nginx restart    