---
# tasks file for user
- name: Create  group for user "{{ username }}"
  become: yes
  group:
    name: "{{ username }}"
    state: present
    gid: "{{ gid }}"

- name: Create a user {{ username }} 
  become: yes              
  user: 
    name: "{{ username }}"
    uid: "{{ id }}"    
    group: "{{ gid }}"
    password: "{{ passwd }}"

- name: Add sudoers priveleges  in a separate file
  become: yes
  copy:
    dest: "/etc/sudoers.d/{{ username }}"
    content: "{{ sudoers }}"
  with_items: "{{ sudoers|default([]) }}"
  