---
# tasks file for nginx-sonar
- name: Add Nginx Repository
  yum_repository:
    name: Nginx
    description: Nginx Centos Repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: no
    enabled: yes
  become: yes

- name: Ensure Nginx Installed
  yum: name=nginx  
  become: yes

- name: change config
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - nginx restart