- name: Check that the nexus.service exists
  stat:
    path: "{{ nexus_service_dest }}"
  register: nexus_service


- debug: msg="{{nexus_service.stat.exists}}"
  when: nexus_service.stat.exists == false
  tags: never

- import_tasks: install_nexus.yml
  when: nexus_service.stat.exists == false