---
# tasks file for java

- name: install dependency 
  become: yes  
  yum:
    name:      
      - wget  
      - vim 
      - java-1.8.0-openjdk-devel
      - unzip  
      - git
  changed_when: False   
    # state: installed

# ------------------------------- delimeter ----------------------------------- # 

- name: Fix jenkins folder permissions
  become: yes
  file:
    path: /opt/jenkins
    owner: jenkins
    group: jenkins        
    mode: 0755        
    recurse: yes
    state: directory
  changed_when: False

