---
# tasks file for jenkins

- name: Deploy Systemd File jenkins.service
  become: yes
  template:
    src: jenkins.service.j2
    dest: /usr/lib/systemd/system/jenkins.service

- name: Add jenkins.war 
  become: yes
  copy:
    src: jenkins.war
    dest: /opt/jenkins
    owner: jenkins
    group: jenkins
    # state: file
  changed_when: False

# - name: add jenkins YUM repository
#   yum_repository:
#     name: Jenkins
#     description: Jenkins YUM repository
#     baseurl: "{{ URL }}"
#     gpgkey: "{{ KEY }}"
#     gpgcheck: yes
#   become: yes

# - name: Jenkins repository
#   become: yes
#   command: |
#     wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo
#     rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
#     yum install jenkins -y
#   changed_when: False

# - name: Install Jenkins
#   yum:
#     name: jenkins
#     state: present
#   become: yes

# - name: Change Jenkins JAVA options
#   lineinfile: 
#     dest=/opt/jenkins
#     regexp=^JENKINS_JAVA_OPTIONS=
#     line=JENKINS_JAVA_OPTIONS="{{ JAVAOPT }}"
#   become: true

- name: Start Jenkins service and enable on boot  
  service:
    name: jenkins
    state: started
    enabled: yes
  become: yes



