---
# tasks file for tomcat
- name: install dependency 
  become: yes  
  yum:
    name:      
      - wget  
      # - vim 
      - httpd-devel
      # - apr
      # - apr-devel
      # - apr-util
      # - apr-util-devel
      # - gcc
      # - gcc-c++
      # - make 
      # - autoconf
      # - libtool
      - java-1.8.0-openjdk-devel
      - unzip  
      # - git
  changed_when: no

- name: Create a user tomcat   
  become: yes              
  user: 
    name: tomcat    
    password: "{{ 'tomcat' | password_hash('sha512', 'mysecretsalt') }}"

- name: create directory for tomcat
  become: yes
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat        
    mode: 0755        
    recurse: yes
    state: directory
  changed_when: no  

- name: unzip tomcat
  become: yes
  become_user: tomcat
  unarchive:
    src: "{{ URL_tomcat }}"
    dest: /opt/tomcat
    remote_src: yes
  args:
    creates: "{{catalina}}"
  changed_when: no

- name: add tomcat-service
  become: yes
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  notify:
    - daemon-reload
    - tomcat-start








