---
# tasks file for common
- name: install dependency 
  become: yes  
  yum:
    name:      
      - wget  
      - vim 
      - unzip  
      - git
    state: installed
  changed_when: False  

- name: create directory for custom facts 
  become: yes  
  file:
    path: /etc/ansible/facts.d
    state: directory