---
# tasks file for jenkins-user
- name: Create a user jenkins   
  become: yes              
  user: 
    name: jenkins
    uid: 1212
    # gui: 1212
    password: "{{ 'jenkins' | password_hash('sha512', 'mysecretsalt') }}"
# add check user and change this part

- name: Create directory jenkins_home
  become: yes       
  file:
    path: "{{ jen_home }}/.ssh"
    state: directory



- name: Copy public key to remote hosts
  become: yes  
  copy:
    src: jenkins.dep
    dest: "{{ jen_home }}/.ssh/authorized_keys"
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Add sudoers priveleges      
  become: yes 
  copy:
    src: jenkins.permissions
    dest: /etc/sudoers.d/jenkins

#        ansible-playbook main.yml -i inventory -e ansible_user=root -k         #

# ------------------------------- delimeter ----------------------------------- # 