- hosts: all
  become: yes
  pre_tasks:
    - name: Create /etc/ansible/facts.d
      file:
        path: /etc/ansible/facts.d
        state: directory
  tags: pre-install

- name: Add common role to all servers
  hosts: all
  roles:
    - role: common
  tags: pre-install    

- name: Create user Jenkins, and so on
  hosts: j-job
  roles:
    - jenkins        
    - nginx
  tags: install

- name: Automated Code Analysis
  hosts: sonar
  roles:
    - sonarServer     
  tags: install

- name: Nexus
  hosts: nexus
  roles: 
    - role: nexus 
  tags: install   

- name: Tomcat
  hosts: tomcat 
  roles:
    - role: tomcat
  tags: install

- name: deploy to tomcat
  hosts: deploy 
  roles:
    - role: deployTomcat
  tags: never

- hosts: all
  become: yes  
  post_tasks:
    - name: custom script
      shell: /vagrant/trash/tools.sh
      changed_when: no
  tags: pre-install