- name: Add common role to all servers
  hosts: farm
  roles:
    - role: common
  tags: pre-install    

- name: Create user Jenkins, and so on
  hosts: j-job
  roles:
    - jenkins        
    - nginx
  tags: install

- name: Automated Code Analysis
  hosts: sonar
  roles:
    - sonarServer     
  tags: install

- name: Nexus
  hosts: nexus
  roles: 
    - role: nexus 
  tags: install   

- name: Tomcat
  hosts: tomcat 
  roles:
    - role: tomcat
  tags: install

# - name: deploy to tomcat
#   hosts: deploy 
#   roles:
#     - role: deployTomcat
#   tags: never