# - name: Add common role to all servers
#   hosts: all
#   roles:
#     - common    

# - name: Create user Jenkins, and so on
#   hosts: j-job
#   roles:
#     - jenkins
#     - nginx

# - name: Automated Code Analysis
#   hosts: sonar
#   roles:
#     - sonarServer     

- name: Nexus
  hosts: nexus
  roles: 
    - nexus 

# - name: Tomcat
#   hosts: tomcat 
#   roles:
#     - tomcat

# - hosts: all
#   become: yes  
#   post_tasks:
#     - name: custom script
#       shell: /vagrant/trash/tools.sh
#       changed_when: no


# First time run as root 
# ansible-playbook playbook.yml 
# -e ansible_user=root -k
# enter in postgresql
# sudo su postgres
# psql

# -------------------- Test Zone -------------------- #
